services:
  web:
    # se estiver usando seu Dockerfile:
    build: .
    # se estiver usando webdevops, troque por image: webdevops/php-apache:8.2
    container_name: sql_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASS: apppass
      DB_NAME: Forum
      USER_IMG_PATH: "/var/www/html/uploads/"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: sql_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Forum           # <-- importante
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5
    container_name: sql_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
