name: OWASP ZAP Scan

on:
  push:
    branches: [ "Corrigido" ]
  pull_request:
    branches: [ "Corrigido" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      #Clona o código
      - name: Checkout do código
        uses: actions/checkout@v4

      #Instala o PHP
      - name: Instalar PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php

      #Inicia o servidor PHP embutido
      - name: Iniciar servidor PHP
        run: |
          php -S localhost:8000 -t src &  # altere "src" para a pasta raiz da sua aplicação
          sleep 10  # espera o servidor subir

      #Instala OWASP ZAP standalone
      - name: Instalar OWASP ZAP
        run: |
          sudo apt-get install -y zaproxy

      #Executa o ZAP Baseline Scan
      - name: Executar OWASP ZAP Baseline Scan
        run: |
          zap.sh -daemon -quickurl http://localhost:8000 -quickout report.html

      #Faz upload do relatório HTML como artefato
      - name: Upload do relatório ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
