name: OWASP ZAP Scan

on:
  push:
    branches: [ "Corrigido" ]
  pull_request:
    branches: [ "Corrigido" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Timeout para o job inteiro

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Instala PHP
      - name: Instalar PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php

      # 3️⃣ Inicia servidor PHP embutido
      - name: Iniciar servidor PHP
        run: |
          php -S localhost:8000 -t src &
          echo $! > php_server.pid
          sleep 5
          # Verifica se o servidor está rodando
          for i in {1..10}; do
            if curl -s http://localhost:8000 > /dev/null; then
              echo "Servidor PHP rodando!"
              break
            fi
            echo "Aguardando servidor... tentativa $i"
            sleep 2
          done

      # 4️⃣ Usa Docker do ZAP (mais confiável)
      - name: Executar OWASP ZAP Baseline Scan
        timeout-minutes: 15
        continue-on-error: true  # Continua mesmo se falhar
        run: |
          mkdir -p $GITHUB_WORKSPACE/reports
          
          # CRÍTICO: Ajusta permissões para o Docker poder escrever
          chmod -R 777 $GITHUB_WORKSPACE/reports
          
          echo "🔍 Iniciando ZAP Scan..."
          echo "📂 Diretório de trabalho: $GITHUB_WORKSPACE/reports"
          
          docker run --network="host" \
            -v $GITHUB_WORKSPACE/reports:/zap/wrk/:rw \
            -u zap \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8000 \
            -r report.html \
            -J report.json \
            -w report.md \
            -d 2>&1 | tee $GITHUB_WORKSPACE/zap_output.log || echo "⚠️ ZAP terminou com código de saída: $?"
          
          echo "✅ Comando ZAP finalizado"
          echo "📋 Últimas 50 linhas do log:"
          tail -50 $GITHUB_WORKSPACE/zap_output.log || echo "Log não disponível"

      # 5️⃣ Debug - Verificar se servidor está acessível
      - name: Testar acesso ao servidor
        if: always()
        run: |
          echo "Testando servidor PHP..."
          curl -v http://localhost:8000 || echo "❌ Servidor não está respondendo"
          echo "Processos PHP rodando:"
          ps aux | grep php || echo "Nenhum processo PHP encontrado"

      # 6️⃣ Verificar se o relatório foi gerado
      - name: Verificar relatórios gerados
        if: always()
        run: |
          echo "📁 Conteúdo do diretório reports:"
          ls -lah $GITHUB_WORKSPACE/reports/ || echo "Diretório reports não existe"
          echo ""
          echo "📁 Conteúdo do workspace:"
          ls -lah $GITHUB_WORKSPACE/
          echo ""
          if [ -f "$GITHUB_WORKSPACE/reports/report.html" ]; then
            echo "✅ Relatório HTML gerado com sucesso"
            wc -l $GITHUB_WORKSPACE/reports/report.html
          else
            echo "❌ Relatório HTML não foi gerado"
          fi
          
          # Mostra log completo do ZAP se existir
          if [ -f "$GITHUB_WORKSPACE/zap_output.log" ]; then
            echo ""
            echo "📄 Log completo do ZAP:"
            cat $GITHUB_WORKSPACE/zap_output.log
          fi

      # 6️⃣ Faz upload do relatório (sempre executa)
      - name: Upload do relatório ZAP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: $GITHUB_WORKSPACE/reports/
          
      # 7️⃣ Cleanup
      - name: Parar servidor PHP
        if: always()
        run: |
          if [ -f php_server.pid ]; then
            kill $(cat php_server.pid) || true
          fi