name: OWASP ZAP Scan

on:
  push:
    branches: [ "Corrigido" ]
  pull_request:
    branches: [ "Corrigido" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    #Clona o código do repositório
    - name: Checkout do código
      uses: actions/checkout@v4

    #Instala o PHP e sobe o servidor embutido
    - name: Iniciar servidor PHP
      run: |
        sudo apt-get update
        sudo apt-get install -y php
        nohup php -S localhost:8000 -t public/ &
        sleep 10  # espera o servidor inicializar

    #Executa o ZAP Baseline Scan
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: 'http://localhost:8000'
        cmd_options: '-a'

    #Salva o relatório HTML como artefato
    - name: Upload do relatório ZAP
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html