name: OWASP ZAP Scan

on:
  push:
    branches: [ "Corrigido" ]
  pull_request:
    branches: [ "Corrigido" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Instala PHP
      - name: Instalar PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php

      # 3️⃣ Inicia servidor PHP embutido
      - name: Iniciar servidor PHP
        run: |
          php -S localhost:8000 -t src &  # altere "src" para a pasta raiz da sua aplicação
          sleep 15  # espera o servidor subir

      # 4️⃣ Baixa e extrai OWASP ZAP
      - name: Baixar OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2_13_0_Linux.tar.gz -O zap.tar.gz
          tar -xzf zap.tar.gz
          chmod +x ZAP_2_13_0/zap.sh

      # 5️⃣ Executa ZAP Baseline Scan
      - name: Executar OWASP ZAP Baseline Scan
        run: |
          ZAP_2_13_0/zap.sh -daemon -quickurl http://localhost:8000 -quickout report.html

      # 6️⃣ Faz upload do relatório HTML
      - name: Upload do relatório ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
